/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdInfo } from './IdInfo';
import {
    IdInfoFromJSON,
    IdInfoFromJSONTyped,
    IdInfoToJSON,
    IdInfoToJSONTyped,
} from './IdInfo';
import type { TeamAwardWinner } from './TeamAwardWinner';
import {
    TeamAwardWinnerFromJSON,
    TeamAwardWinnerFromJSONTyped,
    TeamAwardWinnerToJSON,
    TeamAwardWinnerToJSONTyped,
} from './TeamAwardWinner';

/**
 * 
 * @export
 * @interface Award
 */
export interface Award {
    /**
     * 
     * @type {number}
     * @memberof Award
     */
    id?: number;
    /**
     * 
     * @type {IdInfo}
     * @memberof Award
     */
    event?: IdInfo;
    /**
     * 
     * @type {number}
     * @memberof Award
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof Award
     */
    title?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Award
     */
    qualifications?: Array<string>;
    /**
     * Some awards are given out per tournament or division
     * @type {AwardDesignationEnum}
     * @memberof Award
     */
    designation?: AwardDesignationEnum | null;
    /**
     * 
     * @type {AwardClassificationEnum}
     * @memberof Award
     */
    classification?: AwardClassificationEnum | null;
    /**
     * 
     * @type {Array<TeamAwardWinner>}
     * @memberof Award
     */
    teamWinners?: Array<TeamAwardWinner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Award
     */
    individualWinners?: Array<string>;
}


/**
 * @export
 */
export const AwardDesignationEnum = {
    Tournament: 'tournament',
    Division: 'division'
} as const;
export type AwardDesignationEnum = typeof AwardDesignationEnum[keyof typeof AwardDesignationEnum];

/**
 * @export
 */
export const AwardClassificationEnum = {
    Champion: 'champion',
    Finalist: 'finalist',
    Semifinalist: 'semifinalist',
    Quarterfinalist: 'quarterfinalist'
} as const;
export type AwardClassificationEnum = typeof AwardClassificationEnum[keyof typeof AwardClassificationEnum];


/**
 * Check if a given object implements the Award interface.
 */
export function instanceOfAward(value: object): value is Award {
    return true;
}

export function AwardFromJSON(json: any): Award {
    return AwardFromJSONTyped(json, false);
}

export function AwardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Award {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'event': json['event'] == null ? undefined : IdInfoFromJSON(json['event']),
        'order': json['order'] == null ? undefined : json['order'],
        'title': json['title'] == null ? undefined : json['title'],
        'qualifications': json['qualifications'] == null ? undefined : json['qualifications'],
        'designation': json['designation'] == null ? undefined : json['designation'],
        'classification': json['classification'] == null ? undefined : json['classification'],
        'teamWinners': json['teamWinners'] == null ? undefined : ((json['teamWinners'] as Array<any>).map(TeamAwardWinnerFromJSON)),
        'individualWinners': json['individualWinners'] == null ? undefined : json['individualWinners'],
    };
}

export function AwardToJSON(json: any): Award {
    return AwardToJSONTyped(json, false);
}

export function AwardToJSONTyped(value?: Award | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'event': IdInfoToJSON(value['event']),
        'order': value['order'],
        'title': value['title'],
        'qualifications': value['qualifications'],
        'designation': value['designation'],
        'classification': value['classification'],
        'teamWinners': value['teamWinners'] == null ? undefined : ((value['teamWinners'] as Array<any>).map(TeamAwardWinnerToJSON)),
        'individualWinners': value['individualWinners'],
    };
}

