/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageMeta
 */
export interface PageMeta {
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    currentPage?: number;
    /**
     * 
     * @type {string}
     * @memberof PageMeta
     */
    firstPageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    lastPage?: number;
    /**
     * 
     * @type {string}
     * @memberof PageMeta
     */
    lastPageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PageMeta
     */
    nextPageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PageMeta
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    perPage?: number;
    /**
     * 
     * @type {string}
     * @memberof PageMeta
     */
    prevPageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    to?: number;
    /**
     * 
     * @type {number}
     * @memberof PageMeta
     */
    total?: number;
}

/**
 * Check if a given object implements the PageMeta interface.
 */
export function instanceOfPageMeta(value: object): value is PageMeta {
    return true;
}

export function PageMetaFromJSON(json: any): PageMeta {
    return PageMetaFromJSONTyped(json, false);
}

export function PageMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'] == null ? undefined : json['current_page'],
        'firstPageUrl': json['first_page_url'] == null ? undefined : json['first_page_url'],
        'from': json['from'] == null ? undefined : json['from'],
        'lastPage': json['last_page'] == null ? undefined : json['last_page'],
        'lastPageUrl': json['last_page_url'] == null ? undefined : json['last_page_url'],
        'nextPageUrl': json['next_page_url'] == null ? undefined : json['next_page_url'],
        'path': json['path'] == null ? undefined : json['path'],
        'perPage': json['per_page'] == null ? undefined : json['per_page'],
        'prevPageUrl': json['prev_page_url'] == null ? undefined : json['prev_page_url'],
        'to': json['to'] == null ? undefined : json['to'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function PageMetaToJSON(json: any): PageMeta {
    return PageMetaToJSONTyped(json, false);
}

export function PageMetaToJSONTyped(value?: PageMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'first_page_url': value['firstPageUrl'],
        'from': value['from'],
        'last_page': value['lastPage'],
        'last_page_url': value['lastPageUrl'],
        'next_page_url': value['nextPageUrl'],
        'path': value['path'],
        'per_page': value['perPage'],
        'prev_page_url': value['prevPageUrl'],
        'to': value['to'],
        'total': value['total'],
    };
}

