/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdInfo } from './IdInfo';
import {
    IdInfoFromJSON,
    IdInfoFromJSONTyped,
    IdInfoToJSON,
    IdInfoToJSONTyped,
} from './IdInfo';

/**
 * 
 * @export
 * @interface Ranking
 */
export interface Ranking {
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    id?: number;
    /**
     * 
     * @type {IdInfo}
     * @memberof Ranking
     */
    event?: IdInfo;
    /**
     * 
     * @type {IdInfo}
     * @memberof Ranking
     */
    division?: IdInfo;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    rank?: number;
    /**
     * 
     * @type {IdInfo}
     * @memberof Ranking
     */
    team?: IdInfo;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    wins?: number;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    losses?: number;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    ties?: number;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    wp?: number;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    ap?: number;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    sp?: number;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    highScore?: number;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    averagePoints?: number;
    /**
     * 
     * @type {number}
     * @memberof Ranking
     */
    totalPoints?: number;
}

/**
 * Check if a given object implements the Ranking interface.
 */
export function instanceOfRanking(value: object): value is Ranking {
    return true;
}

export function RankingFromJSON(json: any): Ranking {
    return RankingFromJSONTyped(json, false);
}

export function RankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ranking {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'event': json['event'] == null ? undefined : IdInfoFromJSON(json['event']),
        'division': json['division'] == null ? undefined : IdInfoFromJSON(json['division']),
        'rank': json['rank'] == null ? undefined : json['rank'],
        'team': json['team'] == null ? undefined : IdInfoFromJSON(json['team']),
        'wins': json['wins'] == null ? undefined : json['wins'],
        'losses': json['losses'] == null ? undefined : json['losses'],
        'ties': json['ties'] == null ? undefined : json['ties'],
        'wp': json['wp'] == null ? undefined : json['wp'],
        'ap': json['ap'] == null ? undefined : json['ap'],
        'sp': json['sp'] == null ? undefined : json['sp'],
        'highScore': json['high_score'] == null ? undefined : json['high_score'],
        'averagePoints': json['average_points'] == null ? undefined : json['average_points'],
        'totalPoints': json['total_points'] == null ? undefined : json['total_points'],
    };
}

export function RankingToJSON(json: any): Ranking {
    return RankingToJSONTyped(json, false);
}

export function RankingToJSONTyped(value?: Ranking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'event': IdInfoToJSON(value['event']),
        'division': IdInfoToJSON(value['division']),
        'rank': value['rank'],
        'team': IdInfoToJSON(value['team']),
        'wins': value['wins'],
        'losses': value['losses'],
        'ties': value['ties'],
        'wp': value['wp'],
        'ap': value['ap'],
        'sp': value['sp'],
        'high_score': value['highScore'],
        'average_points': value['averagePoints'],
        'total_points': value['totalPoints'],
    };
}

