/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SkillType } from './SkillType';
import {
    SkillTypeFromJSON,
    SkillTypeFromJSONTyped,
    SkillTypeToJSON,
    SkillTypeToJSONTyped,
} from './SkillType';
import type { IdInfo } from './IdInfo';
import {
    IdInfoFromJSON,
    IdInfoFromJSONTyped,
    IdInfoToJSON,
    IdInfoToJSONTyped,
} from './IdInfo';

/**
 * 
 * @export
 * @interface Skill
 */
export interface Skill {
    /**
     * 
     * @type {number}
     * @memberof Skill
     */
    id?: number;
    /**
     * 
     * @type {IdInfo}
     * @memberof Skill
     */
    event?: IdInfo;
    /**
     * 
     * @type {IdInfo}
     * @memberof Skill
     */
    team?: IdInfo;
    /**
     * 
     * @type {SkillType}
     * @memberof Skill
     */
    type?: SkillType;
    /**
     * 
     * @type {IdInfo}
     * @memberof Skill
     */
    season?: IdInfo;
    /**
     * 
     * @type {IdInfo}
     * @memberof Skill
     */
    division?: IdInfo;
    /**
     * 
     * @type {number}
     * @memberof Skill
     */
    rank?: number;
    /**
     * 
     * @type {number}
     * @memberof Skill
     */
    score?: number;
    /**
     * 
     * @type {number}
     * @memberof Skill
     */
    attempts?: number;
}



/**
 * Check if a given object implements the Skill interface.
 */
export function instanceOfSkill(value: object): value is Skill {
    return true;
}

export function SkillFromJSON(json: any): Skill {
    return SkillFromJSONTyped(json, false);
}

export function SkillFromJSONTyped(json: any, ignoreDiscriminator: boolean): Skill {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'event': json['event'] == null ? undefined : IdInfoFromJSON(json['event']),
        'team': json['team'] == null ? undefined : IdInfoFromJSON(json['team']),
        'type': json['type'] == null ? undefined : SkillTypeFromJSON(json['type']),
        'season': json['season'] == null ? undefined : IdInfoFromJSON(json['season']),
        'division': json['division'] == null ? undefined : IdInfoFromJSON(json['division']),
        'rank': json['rank'] == null ? undefined : json['rank'],
        'score': json['score'] == null ? undefined : json['score'],
        'attempts': json['attempts'] == null ? undefined : json['attempts'],
    };
}

export function SkillToJSON(json: any): Skill {
    return SkillToJSONTyped(json, false);
}

export function SkillToJSONTyped(value?: Skill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'event': IdInfoToJSON(value['event']),
        'team': IdInfoToJSON(value['team']),
        'type': SkillTypeToJSON(value['type']),
        'season': IdInfoToJSON(value['season']),
        'division': IdInfoToJSON(value['division']),
        'rank': value['rank'],
        'score': value['score'],
        'attempts': value['attempts'],
    };
}

