/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventLevel } from './EventLevel';
import {
    EventLevelFromJSON,
    EventLevelFromJSONTyped,
    EventLevelToJSON,
    EventLevelToJSONTyped,
} from './EventLevel';
import type { EventType } from './EventType';
import {
    EventTypeFromJSON,
    EventTypeFromJSONTyped,
    EventTypeToJSON,
    EventTypeToJSONTyped,
} from './EventType';
import type { Division } from './Division';
import {
    DivisionFromJSON,
    DivisionFromJSONTyped,
    DivisionToJSON,
    DivisionToJSONTyped,
} from './Division';
import type { IdInfo } from './IdInfo';
import {
    IdInfoFromJSON,
    IdInfoFromJSONTyped,
    IdInfoToJSON,
    IdInfoToJSONTyped,
} from './IdInfo';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    sku: string;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    end?: Date;
    /**
     * 
     * @type {IdInfo}
     * @memberof Event
     */
    season: IdInfo;
    /**
     * 
     * @type {IdInfo}
     * @memberof Event
     */
    program: IdInfo;
    /**
     * 
     * @type {Location}
     * @memberof Event
     */
    location: Location;
    /**
     * 
     * @type {Array<{ [key: string]: Location; }>}
     * @memberof Event
     */
    locations?: Array<{ [key: string]: Location; }>;
    /**
     * 
     * @type {Array<Division>}
     * @memberof Event
     */
    divisions?: Array<Division>;
    /**
     * 
     * @type {EventLevel}
     * @memberof Event
     */
    level?: EventLevel;
    /**
     * 
     * @type {boolean}
     * @memberof Event
     */
    ongoing?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Event
     */
    awardsFinalized?: boolean;
    /**
     * 
     * @type {EventType}
     * @memberof Event
     */
    eventType?: EventType;
}



/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sku' in value) || value['sku'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('season' in value) || value['season'] === undefined) return false;
    if (!('program' in value) || value['program'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sku': json['sku'],
        'name': json['name'],
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
        'season': IdInfoFromJSON(json['season']),
        'program': IdInfoFromJSON(json['program']),
        'location': LocationFromJSON(json['location']),
        'locations': json['locations'] == null ? undefined : json['locations'],
        'divisions': json['divisions'] == null ? undefined : ((json['divisions'] as Array<any>).map(DivisionFromJSON)),
        'level': json['level'] == null ? undefined : EventLevelFromJSON(json['level']),
        'ongoing': json['ongoing'] == null ? undefined : json['ongoing'],
        'awardsFinalized': json['awards_finalized'] == null ? undefined : json['awards_finalized'],
        'eventType': json['event_type'] == null ? undefined : EventTypeFromJSON(json['event_type']),
    };
}

export function EventToJSON(json: any): Event {
    return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Event | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'sku': value['sku'],
        'name': value['name'],
        'start': value['start'] == null ? value['start'] : value['start'].toISOString(),
        'end': value['end'] == null ? value['end'] : value['end'].toISOString(),
        'season': IdInfoToJSON(value['season']),
        'program': IdInfoToJSON(value['program']),
        'location': LocationToJSON(value['location']),
        'locations': value['locations'],
        'divisions': value['divisions'] == null ? undefined : ((value['divisions'] as Array<any>).map(DivisionToJSON)),
        'level': EventLevelToJSON(value['level']),
        'ongoing': value['ongoing'],
        'awards_finalized': value['awardsFinalized'],
        'event_type': EventTypeToJSON(value['eventType']),
    };
}

