/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Alliance } from './Alliance';
import {
    AllianceFromJSON,
    AllianceFromJSONTyped,
    AllianceToJSON,
    AllianceToJSONTyped,
} from './Alliance';
import type { IdInfo } from './IdInfo';
import {
    IdInfoFromJSON,
    IdInfoFromJSONTyped,
    IdInfoToJSON,
    IdInfoToJSONTyped,
} from './IdInfo';

/**
 * 
 * @export
 * @interface MatchObj
 */
export interface MatchObj {
    /**
     * 
     * @type {number}
     * @memberof MatchObj
     */
    id: number;
    /**
     * 
     * @type {IdInfo}
     * @memberof MatchObj
     */
    event: IdInfo;
    /**
     * 
     * @type {IdInfo}
     * @memberof MatchObj
     */
    division: IdInfo;
    /**
     * 
     * @type {number}
     * @memberof MatchObj
     */
    round: number;
    /**
     * 
     * @type {number}
     * @memberof MatchObj
     */
    instance: number;
    /**
     * 
     * @type {number}
     * @memberof MatchObj
     */
    matchnum: number;
    /**
     * 
     * @type {Date}
     * @memberof MatchObj
     */
    scheduled?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MatchObj
     */
    started?: Date;
    /**
     * 
     * @type {string}
     * @memberof MatchObj
     */
    field?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MatchObj
     */
    scored: boolean;
    /**
     * 
     * @type {string}
     * @memberof MatchObj
     */
    name: string;
    /**
     * 
     * @type {Array<Alliance>}
     * @memberof MatchObj
     */
    alliances: Array<Alliance>;
}

/**
 * Check if a given object implements the MatchObj interface.
 */
export function instanceOfMatchObj(value: object): value is MatchObj {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('division' in value) || value['division'] === undefined) return false;
    if (!('round' in value) || value['round'] === undefined) return false;
    if (!('instance' in value) || value['instance'] === undefined) return false;
    if (!('matchnum' in value) || value['matchnum'] === undefined) return false;
    if (!('scored' in value) || value['scored'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('alliances' in value) || value['alliances'] === undefined) return false;
    return true;
}

export function MatchObjFromJSON(json: any): MatchObj {
    return MatchObjFromJSONTyped(json, false);
}

export function MatchObjFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchObj {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'event': IdInfoFromJSON(json['event']),
        'division': IdInfoFromJSON(json['division']),
        'round': json['round'],
        'instance': json['instance'],
        'matchnum': json['matchnum'],
        'scheduled': json['scheduled'] == null ? undefined : (new Date(json['scheduled'])),
        'started': json['started'] == null ? undefined : (new Date(json['started'])),
        'field': json['field'] == null ? undefined : json['field'],
        'scored': json['scored'],
        'name': json['name'],
        'alliances': ((json['alliances'] as Array<any>).map(AllianceFromJSON)),
    };
}

export function MatchObjToJSON(json: any): MatchObj {
    return MatchObjToJSONTyped(json, false);
}

export function MatchObjToJSONTyped(value?: MatchObj | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'event': IdInfoToJSON(value['event']),
        'division': IdInfoToJSON(value['division']),
        'round': value['round'],
        'instance': value['instance'],
        'matchnum': value['matchnum'],
        'scheduled': value['scheduled'] == null ? value['scheduled'] : value['scheduled'].toISOString(),
        'started': value['started'] == null ? value['started'] : value['started'].toISOString(),
        'field': value['field'],
        'scored': value['scored'],
        'name': value['name'],
        'alliances': ((value['alliances'] as Array<any>).map(AllianceToJSON)),
    };
}

