/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { Season } from './Season';
import {
    SeasonFromJSON,
    SeasonFromJSONTyped,
    SeasonToJSON,
    SeasonToJSONTyped,
} from './Season';

/**
 * 
 * @export
 * @interface PaginatedSeason
 */
export interface PaginatedSeason {
    /**
     * 
     * @type {PageMeta}
     * @memberof PaginatedSeason
     */
    meta?: PageMeta;
    /**
     * 
     * @type {Array<Season>}
     * @memberof PaginatedSeason
     */
    data?: Array<Season>;
}

/**
 * Check if a given object implements the PaginatedSeason interface.
 */
export function instanceOfPaginatedSeason(value: object): value is PaginatedSeason {
    return true;
}

export function PaginatedSeasonFromJSON(json: any): PaginatedSeason {
    return PaginatedSeasonFromJSONTyped(json, false);
}

export function PaginatedSeasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSeason {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PageMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SeasonFromJSON)),
    };
}

export function PaginatedSeasonToJSON(json: any): PaginatedSeason {
    return PaginatedSeasonToJSONTyped(json, false);
}

export function PaginatedSeasonToJSONTyped(value?: PaginatedSeason | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PageMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SeasonToJSON)),
    };
}

