/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdInfo } from './IdInfo';
import {
    IdInfoFromJSON,
    IdInfoFromJSONTyped,
    IdInfoToJSON,
    IdInfoToJSONTyped,
} from './IdInfo';

/**
 * 
 * @export
 * @interface AllianceTeam
 */
export interface AllianceTeam {
    /**
     * 
     * @type {IdInfo}
     * @memberof AllianceTeam
     */
    team?: IdInfo;
    /**
     * 
     * @type {boolean}
     * @memberof AllianceTeam
     */
    sitting?: boolean;
}

/**
 * Check if a given object implements the AllianceTeam interface.
 */
export function instanceOfAllianceTeam(value: object): value is AllianceTeam {
    return true;
}

export function AllianceTeamFromJSON(json: any): AllianceTeam {
    return AllianceTeamFromJSONTyped(json, false);
}

export function AllianceTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllianceTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'team': json['team'] == null ? undefined : IdInfoFromJSON(json['team']),
        'sitting': json['sitting'] == null ? undefined : json['sitting'],
    };
}

export function AllianceTeamToJSON(json: any): AllianceTeam {
    return AllianceTeamToJSONTyped(json, false);
}

export function AllianceTeamToJSONTyped(value?: AllianceTeam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'team': IdInfoToJSON(value['team']),
        'sitting': value['sitting'],
    };
}

