/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EventLevel = {
    World: 'World',
    National: 'National',
    Regional: 'Regional',
    State: 'State',
    Signature: 'Signature',
    Other: 'Other'
} as const;
export type EventLevel = typeof EventLevel[keyof typeof EventLevel];


export function instanceOfEventLevel(value: any): boolean {
    for (const key in EventLevel) {
        if (Object.prototype.hasOwnProperty.call(EventLevel, key)) {
            if (EventLevel[key as keyof typeof EventLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EventLevelFromJSON(json: any): EventLevel {
    return EventLevelFromJSONTyped(json, false);
}

export function EventLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventLevel {
    return json as EventLevel;
}

export function EventLevelToJSON(value?: EventLevel | null): any {
    return value as any;
}

export function EventLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): EventLevel {
    return value as EventLevel;
}

