/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdInfo
 */
export interface IdInfo {
    /**
     * 
     * @type {number}
     * @memberof IdInfo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof IdInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IdInfo
     */
    code?: string | null;
}

/**
 * Check if a given object implements the IdInfo interface.
 */
export function instanceOfIdInfo(value: object): value is IdInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function IdInfoFromJSON(json: any): IdInfo {
    return IdInfoFromJSONTyped(json, false);
}

export function IdInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function IdInfoToJSON(json: any): IdInfo {
    return IdInfoToJSONTyped(json, false);
}

export function IdInfoToJSONTyped(value?: IdInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
    };
}

