/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { Award } from './Award';
import {
    AwardFromJSON,
    AwardFromJSONTyped,
    AwardToJSON,
    AwardToJSONTyped,
} from './Award';

/**
 * 
 * @export
 * @interface PaginatedAward
 */
export interface PaginatedAward {
    /**
     * 
     * @type {PageMeta}
     * @memberof PaginatedAward
     */
    meta?: PageMeta;
    /**
     * 
     * @type {Array<Award>}
     * @memberof PaginatedAward
     */
    data?: Array<Award>;
}

/**
 * Check if a given object implements the PaginatedAward interface.
 */
export function instanceOfPaginatedAward(value: object): value is PaginatedAward {
    return true;
}

export function PaginatedAwardFromJSON(json: any): PaginatedAward {
    return PaginatedAwardFromJSONTyped(json, false);
}

export function PaginatedAwardFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAward {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PageMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AwardFromJSON)),
    };
}

export function PaginatedAwardToJSON(json: any): PaginatedAward {
    return PaginatedAwardToJSONTyped(json, false);
}

export function PaginatedAwardToJSONTyped(value?: PaginatedAward | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PageMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AwardToJSON)),
    };
}

