/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Program
 */
export interface Program {
    /**
     * 
     * @type {number}
     * @memberof Program
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Program
     */
    abbr?: string;
    /**
     * 
     * @type {string}
     * @memberof Program
     */
    name?: string;
}

/**
 * Check if a given object implements the Program interface.
 */
export function instanceOfProgram(value: object): value is Program {
    return true;
}

export function ProgramFromJSON(json: any): Program {
    return ProgramFromJSONTyped(json, false);
}

export function ProgramFromJSONTyped(json: any, ignoreDiscriminator: boolean): Program {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'abbr': json['abbr'] == null ? undefined : json['abbr'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ProgramToJSON(json: any): Program {
    return ProgramToJSONTyped(json, false);
}

export function ProgramToJSONTyped(value?: Program | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'abbr': value['abbr'],
        'name': value['name'],
    };
}

