/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AllianceTeam } from './AllianceTeam';
import {
    AllianceTeamFromJSON,
    AllianceTeamFromJSONTyped,
    AllianceTeamToJSON,
    AllianceTeamToJSONTyped,
} from './AllianceTeam';

/**
 * 
 * @export
 * @interface Alliance
 */
export interface Alliance {
    /**
     * 
     * @type {AllianceColorEnum}
     * @memberof Alliance
     */
    color: AllianceColorEnum;
    /**
     * 
     * @type {number}
     * @memberof Alliance
     */
    score: number;
    /**
     * 
     * @type {Array<AllianceTeam>}
     * @memberof Alliance
     */
    teams: Array<AllianceTeam>;
}


/**
 * @export
 */
export const AllianceColorEnum = {
    Red: 'red',
    Blue: 'blue'
} as const;
export type AllianceColorEnum = typeof AllianceColorEnum[keyof typeof AllianceColorEnum];


/**
 * Check if a given object implements the Alliance interface.
 */
export function instanceOfAlliance(value: object): value is Alliance {
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('teams' in value) || value['teams'] === undefined) return false;
    return true;
}

export function AllianceFromJSON(json: any): Alliance {
    return AllianceFromJSONTyped(json, false);
}

export function AllianceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Alliance {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'],
        'score': json['score'],
        'teams': ((json['teams'] as Array<any>).map(AllianceTeamFromJSON)),
    };
}

export function AllianceToJSON(json: any): Alliance {
    return AllianceToJSONTyped(json, false);
}

export function AllianceToJSONTyped(value?: Alliance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'score': value['score'],
        'teams': ((value['teams'] as Array<any>).map(AllianceTeamToJSON)),
    };
}

