/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Division
 */
export interface Division {
    /**
     * 
     * @type {number}
     * @memberof Division
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Division
     */
    order?: number;
}

/**
 * Check if a given object implements the Division interface.
 */
export function instanceOfDivision(value: object): value is Division {
    return true;
}

export function DivisionFromJSON(json: any): Division {
    return DivisionFromJSONTyped(json, false);
}

export function DivisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Division {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function DivisionToJSON(json: any): Division {
    return DivisionToJSONTyped(json, false);
}

export function DivisionToJSONTyped(value?: Division | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'order': value['order'],
    };
}

