/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Grade = {
    College: 'College',
    HighSchool: 'High School',
    MiddleSchool: 'Middle School',
    ElementarySchool: 'Elementary School'
} as const;
export type Grade = typeof Grade[keyof typeof Grade];


export function instanceOfGrade(value: any): boolean {
    for (const key in Grade) {
        if (Object.prototype.hasOwnProperty.call(Grade, key)) {
            if (Grade[key as keyof typeof Grade] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GradeFromJSON(json: any): Grade {
    return GradeFromJSONTyped(json, false);
}

export function GradeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Grade {
    return json as Grade;
}

export function GradeToJSON(value?: Grade | null): any {
    return value as any;
}

export function GradeToJSONTyped(value: any, ignoreDiscriminator: boolean): Grade {
    return value as Grade;
}

