/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { Event } from './Event';
import {
    EventFromJSON,
    EventFromJSONTyped,
    EventToJSON,
    EventToJSONTyped,
} from './Event';

/**
 * 
 * @export
 * @interface PaginatedEvent
 */
export interface PaginatedEvent {
    /**
     * 
     * @type {PageMeta}
     * @memberof PaginatedEvent
     */
    meta?: PageMeta;
    /**
     * 
     * @type {Array<Event>}
     * @memberof PaginatedEvent
     */
    data?: Array<Event>;
}

/**
 * Check if a given object implements the PaginatedEvent interface.
 */
export function instanceOfPaginatedEvent(value: object): value is PaginatedEvent {
    return true;
}

export function PaginatedEventFromJSON(json: any): PaginatedEvent {
    return PaginatedEventFromJSONTyped(json, false);
}

export function PaginatedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PageMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EventFromJSON)),
    };
}

export function PaginatedEventToJSON(json: any): PaginatedEvent {
    return PaginatedEventToJSONTyped(json, false);
}

export function PaginatedEventToJSONTyped(value?: PaginatedEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PageMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EventToJSON)),
    };
}

