/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { MatchObj } from './MatchObj';
import {
    MatchObjFromJSON,
    MatchObjFromJSONTyped,
    MatchObjToJSON,
    MatchObjToJSONTyped,
} from './MatchObj';

/**
 * 
 * @export
 * @interface PaginatedMatch
 */
export interface PaginatedMatch {
    /**
     * 
     * @type {PageMeta}
     * @memberof PaginatedMatch
     */
    meta?: PageMeta;
    /**
     * 
     * @type {Array<MatchObj>}
     * @memberof PaginatedMatch
     */
    data?: Array<MatchObj>;
}

/**
 * Check if a given object implements the PaginatedMatch interface.
 */
export function instanceOfPaginatedMatch(value: object): value is PaginatedMatch {
    return true;
}

export function PaginatedMatchFromJSON(json: any): PaginatedMatch {
    return PaginatedMatchFromJSONTyped(json, false);
}

export function PaginatedMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedMatch {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PageMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MatchObjFromJSON)),
    };
}

export function PaginatedMatchToJSON(json: any): PaginatedMatch {
    return PaginatedMatchToJSONTyped(json, false);
}

export function PaginatedMatchToJSONTyped(value?: PaginatedMatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PageMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MatchObjToJSON)),
    };
}

