/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Skill } from './Skill';
import {
    SkillFromJSON,
    SkillFromJSONTyped,
    SkillToJSON,
    SkillToJSONTyped,
} from './Skill';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';

/**
 * 
 * @export
 * @interface PaginatedSkill
 */
export interface PaginatedSkill {
    /**
     * 
     * @type {PageMeta}
     * @memberof PaginatedSkill
     */
    meta?: PageMeta;
    /**
     * 
     * @type {Array<Skill>}
     * @memberof PaginatedSkill
     */
    data?: Array<Skill>;
}

/**
 * Check if a given object implements the PaginatedSkill interface.
 */
export function instanceOfPaginatedSkill(value: object): value is PaginatedSkill {
    return true;
}

export function PaginatedSkillFromJSON(json: any): PaginatedSkill {
    return PaginatedSkillFromJSONTyped(json, false);
}

export function PaginatedSkillFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSkill {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PageMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SkillFromJSON)),
    };
}

export function PaginatedSkillToJSON(json: any): PaginatedSkill {
    return PaginatedSkillToJSONTyped(json, false);
}

export function PaginatedSkillToJSONTyped(value?: PaginatedSkill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PageMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SkillToJSON)),
    };
}

