/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339.
 *
 * The version of the OpenAPI document: 1.0.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { IdInfo } from "./IdInfo";
import {
  IdInfoFromJSON,
  IdInfoFromJSONTyped,
  IdInfoToJSON,
  IdInfoToJSONTyped,
} from "./IdInfo";

/**
 *
 * @export
 * @interface Season
 */
export interface Season {
  /**
   *
   * @type {number}
   * @memberof Season
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Season
   */
  name?: string;
  /**
   *
   * @type {IdInfo}
   * @memberof Season
   */
  program?: IdInfo;
  /**
   *
   * @type {Date}
   * @memberof Season
   */
  start?: Date;
  /**
   *
   * @type {Date}
   * @memberof Season
   */
  end?: Date;
  /**
   *
   * @type {number}
   * @memberof Season
   */
  yearsStart?: number;
  /**
   *
   * @type {number}
   * @memberof Season
   */
  yearsEnd?: number;
}

/**
 * Check if a given object implements the Season interface.
 */
export function instanceOfSeason(value: object): value is Season {
  return true;
}

const parseLocalCalendarDate = (s: string): Date => {
  const m = s.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (m) return new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
  return new Date(s);
};

export function SeasonFromJSON(json: any): Season {
  return SeasonFromJSONTyped(json, false);
}

export function SeasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Season {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    program: json["program"] == null ? undefined : IdInfoFromJSON(json["program"]),
    start: json["start"] == null ? undefined : parseLocalCalendarDate(json["start"]),
    end: json["end"] == null ? undefined : parseLocalCalendarDate(json["end"]),
    yearsStart: json["years_start"] == null ? undefined : json["years_start"],
    yearsEnd: json["years_end"] == null ? undefined : json["years_end"],
  };
}

export function SeasonToJSON(json: any): Season {
  return SeasonToJSONTyped(json, false);
}

export function SeasonToJSONTyped(
  value?: Season | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    name: value["name"],
    program: IdInfoToJSON(value["program"]),
    start: value["start"] == null ? value["start"] : value["start"].toISOString(),
    end: value["end"] == null ? value["end"] : value["end"].toISOString(),
    years_start: value["yearsStart"],
    years_end: value["yearsEnd"],
  };
}
