/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Program } from './Program';
import {
    ProgramFromJSON,
    ProgramFromJSONTyped,
    ProgramToJSON,
    ProgramToJSONTyped,
} from './Program';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';

/**
 * 
 * @export
 * @interface PaginatedProgram
 */
export interface PaginatedProgram {
    /**
     * 
     * @type {PageMeta}
     * @memberof PaginatedProgram
     */
    meta?: PageMeta;
    /**
     * 
     * @type {Array<Program>}
     * @memberof PaginatedProgram
     */
    data?: Array<Program>;
}

/**
 * Check if a given object implements the PaginatedProgram interface.
 */
export function instanceOfPaginatedProgram(value: object): value is PaginatedProgram {
    return true;
}

export function PaginatedProgramFromJSON(json: any): PaginatedProgram {
    return PaginatedProgramFromJSONTyped(json, false);
}

export function PaginatedProgramFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedProgram {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PageMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ProgramFromJSON)),
    };
}

export function PaginatedProgramToJSON(json: any): PaginatedProgram {
    return PaginatedProgramToJSONTyped(json, false);
}

export function PaginatedProgramToJSONTyped(value?: PaginatedProgram | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PageMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ProgramToJSON)),
    };
}

