/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';
import type { Team } from './Team';
import {
    TeamFromJSON,
    TeamFromJSONTyped,
    TeamToJSON,
    TeamToJSONTyped,
} from './Team';

/**
 * 
 * @export
 * @interface PaginatedTeam
 */
export interface PaginatedTeam {
    /**
     * 
     * @type {PageMeta}
     * @memberof PaginatedTeam
     */
    meta?: PageMeta;
    /**
     * 
     * @type {Array<Team>}
     * @memberof PaginatedTeam
     */
    data?: Array<Team>;
}

/**
 * Check if a given object implements the PaginatedTeam interface.
 */
export function instanceOfPaginatedTeam(value: object): value is PaginatedTeam {
    return true;
}

export function PaginatedTeamFromJSON(json: any): PaginatedTeam {
    return PaginatedTeamFromJSONTyped(json, false);
}

export function PaginatedTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PageMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TeamFromJSON)),
    };
}

export function PaginatedTeamToJSON(json: any): PaginatedTeam {
    return PaginatedTeamToJSONTyped(json, false);
}

export function PaginatedTeamToJSONTyped(value?: PaginatedTeam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PageMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TeamToJSON)),
    };
}

