/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ranking } from './Ranking';
import {
    RankingFromJSON,
    RankingFromJSONTyped,
    RankingToJSON,
    RankingToJSONTyped,
} from './Ranking';
import type { PageMeta } from './PageMeta';
import {
    PageMetaFromJSON,
    PageMetaFromJSONTyped,
    PageMetaToJSON,
    PageMetaToJSONTyped,
} from './PageMeta';

/**
 * 
 * @export
 * @interface PaginatedRanking
 */
export interface PaginatedRanking {
    /**
     * 
     * @type {PageMeta}
     * @memberof PaginatedRanking
     */
    meta?: PageMeta;
    /**
     * 
     * @type {Array<Ranking>}
     * @memberof PaginatedRanking
     */
    data?: Array<Ranking>;
}

/**
 * Check if a given object implements the PaginatedRanking interface.
 */
export function instanceOfPaginatedRanking(value: object): value is PaginatedRanking {
    return true;
}

export function PaginatedRankingFromJSON(json: any): PaginatedRanking {
    return PaginatedRankingFromJSONTyped(json, false);
}

export function PaginatedRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRanking {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : PageMetaFromJSON(json['meta']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RankingFromJSON)),
    };
}

export function PaginatedRankingToJSON(json: any): PaginatedRanking {
    return PaginatedRankingToJSONTyped(json, false);
}

export function PaginatedRankingToJSONTyped(value?: PaginatedRanking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': PageMetaToJSON(value['meta']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RankingToJSON)),
    };
}

