/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdInfo } from './IdInfo';
import {
    IdInfoFromJSON,
    IdInfoFromJSONTyped,
    IdInfoToJSON,
    IdInfoToJSONTyped,
} from './IdInfo';

/**
 * 
 * @export
 * @interface TeamAwardWinner
 */
export interface TeamAwardWinner {
    /**
     * 
     * @type {IdInfo}
     * @memberof TeamAwardWinner
     */
    division?: IdInfo;
    /**
     * 
     * @type {IdInfo}
     * @memberof TeamAwardWinner
     */
    team?: IdInfo;
}

/**
 * Check if a given object implements the TeamAwardWinner interface.
 */
export function instanceOfTeamAwardWinner(value: object): value is TeamAwardWinner {
    return true;
}

export function TeamAwardWinnerFromJSON(json: any): TeamAwardWinner {
    return TeamAwardWinnerFromJSONTyped(json, false);
}

export function TeamAwardWinnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamAwardWinner {
    if (json == null) {
        return json;
    }
    return {
        
        'division': json['division'] == null ? undefined : IdInfoFromJSON(json['division']),
        'team': json['team'] == null ? undefined : IdInfoFromJSON(json['team']),
    };
}

export function TeamAwardWinnerToJSON(json: any): TeamAwardWinner {
    return TeamAwardWinnerToJSONTyped(json, false);
}

export function TeamAwardWinnerToJSONTyped(value?: TeamAwardWinner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'division': IdInfoToJSON(value['division']),
        'team': IdInfoToJSON(value['team']),
    };
}

