/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedEvent,
  PaginatedSeason,
  Season,
} from '../models/index';
import {
    PaginatedEventFromJSON,
    PaginatedEventToJSON,
    PaginatedSeasonFromJSON,
    PaginatedSeasonToJSON,
    SeasonFromJSON,
    SeasonToJSON,
} from '../models/index';

export interface SeasonGetEventsRequest {
    id: number;
    sku?: Array<string>;
    team?: Array<number>;
    start?: Date;
    end?: Date;
    level?: Array<SeasonGetEventsLevelEnum>;
}

export interface SeasonGetSeasonRequest {
    id: number;
}

export interface SeasonGetSeasonsRequest {
    id?: Array<number>;
    program?: Array<number>;
    team?: Array<number>;
    start?: Date;
    end?: Date;
    active?: boolean;
}

/**
 * 
 */
export class SeasonApi extends runtime.BaseAPI {

    /**
     * Creates request options for seasonGetEvents without sending the request
     */
    async seasonGetEventsRequestOpts(requestParameters: SeasonGetEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling seasonGetEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sku'] != null) {
            queryParameters['sku[]'] = requestParameters['sku'];
        }

        if (requestParameters['team'] != null) {
            queryParameters['team[]'] = requestParameters['team'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['level'] != null) {
            queryParameters['level[]'] = requestParameters['level'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/seasons/{id}/events`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Events for a given Season
     */
    async seasonGetEventsRaw(requestParameters: SeasonGetEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedEvent>> {
        const requestOptions = await this.seasonGetEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedEventFromJSON(jsonValue));
    }

    /**
     * Gets a List of Events for a given Season
     */
    async seasonGetEvents(requestParameters: SeasonGetEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedEvent> {
        const response = await this.seasonGetEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for seasonGetSeason without sending the request
     */
    async seasonGetSeasonRequestOpts(requestParameters: SeasonGetSeasonRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling seasonGetSeason().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/seasons/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a single Season
     */
    async seasonGetSeasonRaw(requestParameters: SeasonGetSeasonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Season>> {
        const requestOptions = await this.seasonGetSeasonRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SeasonFromJSON(jsonValue));
    }

    /**
     * Gets a single Season
     */
    async seasonGetSeason(requestParameters: SeasonGetSeasonRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Season> {
        const response = await this.seasonGetSeasonRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for seasonGetSeasons without sending the request
     */
    async seasonGetSeasonsRequestOpts(requestParameters: SeasonGetSeasonsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id[]'] = requestParameters['id'];
        }

        if (requestParameters['program'] != null) {
            queryParameters['program[]'] = requestParameters['program'];
        }

        if (requestParameters['team'] != null) {
            queryParameters['team[]'] = requestParameters['team'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/seasons`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Seasons
     */
    async seasonGetSeasonsRaw(requestParameters: SeasonGetSeasonsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSeason>> {
        const requestOptions = await this.seasonGetSeasonsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSeasonFromJSON(jsonValue));
    }

    /**
     * Gets a List of Seasons
     */
    async seasonGetSeasons(requestParameters: SeasonGetSeasonsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSeason> {
        const response = await this.seasonGetSeasonsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SeasonGetEventsLevelEnum = {
    World: 'World',
    National: 'National',
    State: 'State',
    Signature: 'Signature',
    Other: 'Other'
} as const;
export type SeasonGetEventsLevelEnum = typeof SeasonGetEventsLevelEnum[keyof typeof SeasonGetEventsLevelEnum];
