/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Event,
  EventType,
  PaginatedAward,
  PaginatedEvent,
  PaginatedMatch,
  PaginatedRanking,
  PaginatedSkill,
  PaginatedTeam,
} from '../models/index';
import {
    EventFromJSON,
    EventToJSON,
    EventTypeFromJSON,
    EventTypeToJSON,
    PaginatedAwardFromJSON,
    PaginatedAwardToJSON,
    PaginatedEventFromJSON,
    PaginatedEventToJSON,
    PaginatedMatchFromJSON,
    PaginatedMatchToJSON,
    PaginatedRankingFromJSON,
    PaginatedRankingToJSON,
    PaginatedSkillFromJSON,
    PaginatedSkillToJSON,
    PaginatedTeamFromJSON,
    PaginatedTeamToJSON,
} from '../models/index';

export interface EventGetAwardsRequest {
    id: number;
    team?: Array<number>;
    winner?: Array<string>;
}

export interface EventGetDivisionFinalistRankingsRequest {
    id: number;
    div: number;
    team?: Array<number>;
    rank?: Array<number>;
}

export interface EventGetDivisionMatchesRequest {
    id: number;
    div: number;
    team?: Array<number>;
    round?: Array<number>;
    instance?: Array<number>;
    matchnum?: Array<number>;
}

export interface EventGetDivisionRankingsRequest {
    id: number;
    div: number;
    team?: Array<number>;
    rank?: Array<number>;
}

export interface EventGetEventRequest {
    id: number;
}

export interface EventGetEventsRequest {
    id?: Array<number>;
    sku?: Array<string>;
    team?: Array<number>;
    season?: Array<number>;
    start?: Date;
    end?: Date;
    region?: string;
    level?: Array<EventGetEventsLevelEnum>;
    myEvents?: boolean;
    eventTypes?: Array<EventType>;
}

export interface EventGetSkillsRequest {
    id: number;
    team?: Array<number>;
    type?: Array<EventGetSkillsTypeEnum>;
}

export interface EventGetTeamsRequest {
    id: number;
    number?: Array<string>;
    registered?: boolean;
    grade?: Array<EventGetTeamsGradeEnum>;
    country?: Array<string>;
    myTeams?: boolean;
}

/**
 * 
 */
export class EventApi extends runtime.BaseAPI {

    /**
     * Creates request options for eventGetAwards without sending the request
     */
    async eventGetAwardsRequestOpts(requestParameters: EventGetAwardsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling eventGetAwards().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['team'] != null) {
            queryParameters['team[]'] = requestParameters['team'];
        }

        if (requestParameters['winner'] != null) {
            queryParameters['winner[]'] = requestParameters['winner'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{id}/awards`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Awards at a given Event
     */
    async eventGetAwardsRaw(requestParameters: EventGetAwardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedAward>> {
        const requestOptions = await this.eventGetAwardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedAwardFromJSON(jsonValue));
    }

    /**
     * Gets a List of Awards at a given Event
     */
    async eventGetAwards(requestParameters: EventGetAwardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedAward> {
        const response = await this.eventGetAwardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventGetDivisionFinalistRankings without sending the request
     */
    async eventGetDivisionFinalistRankingsRequestOpts(requestParameters: EventGetDivisionFinalistRankingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling eventGetDivisionFinalistRankings().'
            );
        }

        if (requestParameters['div'] == null) {
            throw new runtime.RequiredError(
                'div',
                'Required parameter "div" was null or undefined when calling eventGetDivisionFinalistRankings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['team'] != null) {
            queryParameters['team[]'] = requestParameters['team'];
        }

        if (requestParameters['rank'] != null) {
            queryParameters['rank[]'] = requestParameters['rank'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{id}/divisions/{div}/finalistRankings`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"div"}}`, encodeURIComponent(String(requestParameters['div'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Finalist Rankings for a single Division of an Event
     */
    async eventGetDivisionFinalistRankingsRaw(requestParameters: EventGetDivisionFinalistRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedRanking>> {
        const requestOptions = await this.eventGetDivisionFinalistRankingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedRankingFromJSON(jsonValue));
    }

    /**
     * Gets a List of Finalist Rankings for a single Division of an Event
     */
    async eventGetDivisionFinalistRankings(requestParameters: EventGetDivisionFinalistRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedRanking> {
        const response = await this.eventGetDivisionFinalistRankingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventGetDivisionMatches without sending the request
     */
    async eventGetDivisionMatchesRequestOpts(requestParameters: EventGetDivisionMatchesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling eventGetDivisionMatches().'
            );
        }

        if (requestParameters['div'] == null) {
            throw new runtime.RequiredError(
                'div',
                'Required parameter "div" was null or undefined when calling eventGetDivisionMatches().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['team'] != null) {
            queryParameters['team[]'] = requestParameters['team'];
        }

        if (requestParameters['round'] != null) {
            queryParameters['round[]'] = requestParameters['round'];
        }

        if (requestParameters['instance'] != null) {
            queryParameters['instance[]'] = requestParameters['instance'];
        }

        if (requestParameters['matchnum'] != null) {
            queryParameters['matchnum[]'] = requestParameters['matchnum'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{id}/divisions/{div}/matches`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"div"}}`, encodeURIComponent(String(requestParameters['div'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Matches for a single Division of an Event
     */
    async eventGetDivisionMatchesRaw(requestParameters: EventGetDivisionMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedMatch>> {
        const requestOptions = await this.eventGetDivisionMatchesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedMatchFromJSON(jsonValue));
    }

    /**
     * Gets a List of Matches for a single Division of an Event
     */
    async eventGetDivisionMatches(requestParameters: EventGetDivisionMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedMatch> {
        const response = await this.eventGetDivisionMatchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventGetDivisionRankings without sending the request
     */
    async eventGetDivisionRankingsRequestOpts(requestParameters: EventGetDivisionRankingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling eventGetDivisionRankings().'
            );
        }

        if (requestParameters['div'] == null) {
            throw new runtime.RequiredError(
                'div',
                'Required parameter "div" was null or undefined when calling eventGetDivisionRankings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['team'] != null) {
            queryParameters['team[]'] = requestParameters['team'];
        }

        if (requestParameters['rank'] != null) {
            queryParameters['rank[]'] = requestParameters['rank'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{id}/divisions/{div}/rankings`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"div"}}`, encodeURIComponent(String(requestParameters['div'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Rankings for a single Division of an Event
     */
    async eventGetDivisionRankingsRaw(requestParameters: EventGetDivisionRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedRanking>> {
        const requestOptions = await this.eventGetDivisionRankingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedRankingFromJSON(jsonValue));
    }

    /**
     * Gets a List of Rankings for a single Division of an Event
     */
    async eventGetDivisionRankings(requestParameters: EventGetDivisionRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedRanking> {
        const response = await this.eventGetDivisionRankingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventGetEvent without sending the request
     */
    async eventGetEventRequestOpts(requestParameters: EventGetEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling eventGetEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a Single Event
     */
    async eventGetEventRaw(requestParameters: EventGetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Event>> {
        const requestOptions = await this.eventGetEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventFromJSON(jsonValue));
    }

    /**
     * Gets a Single Event
     */
    async eventGetEvent(requestParameters: EventGetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Event> {
        const response = await this.eventGetEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventGetEvents without sending the request
     */
    async eventGetEventsRequestOpts(requestParameters: EventGetEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id[]'] = requestParameters['id'];
        }

        if (requestParameters['sku'] != null) {
            queryParameters['sku[]'] = requestParameters['sku'];
        }

        if (requestParameters['team'] != null) {
            queryParameters['team[]'] = requestParameters['team'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season[]'] = requestParameters['season'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['region'] != null) {
            queryParameters['region'] = requestParameters['region'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level[]'] = requestParameters['level'];
        }

        if (requestParameters['myEvents'] != null) {
            queryParameters['myEvents'] = requestParameters['myEvents'];
        }

        if (requestParameters['eventTypes'] != null) {
            queryParameters['eventTypes[]'] = requestParameters['eventTypes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Events
     */
    async eventGetEventsRaw(requestParameters: EventGetEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedEvent>> {
        const requestOptions = await this.eventGetEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedEventFromJSON(jsonValue));
    }

    /**
     * Gets a List of Events
     */
    async eventGetEvents(requestParameters: EventGetEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedEvent> {
        const response = await this.eventGetEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventGetSkills without sending the request
     */
    async eventGetSkillsRequestOpts(requestParameters: EventGetSkillsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling eventGetSkills().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['team'] != null) {
            queryParameters['team[]'] = requestParameters['team'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type[]'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{id}/skills`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Skills runs performed at a given Event
     */
    async eventGetSkillsRaw(requestParameters: EventGetSkillsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSkill>> {
        const requestOptions = await this.eventGetSkillsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSkillFromJSON(jsonValue));
    }

    /**
     * Gets a List of Skills runs performed at a given Event
     */
    async eventGetSkills(requestParameters: EventGetSkillsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSkill> {
        const response = await this.eventGetSkillsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eventGetTeams without sending the request
     */
    async eventGetTeamsRequestOpts(requestParameters: EventGetTeamsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling eventGetTeams().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['number'] != null) {
            queryParameters['number[]'] = requestParameters['number'];
        }

        if (requestParameters['registered'] != null) {
            queryParameters['registered'] = requestParameters['registered'];
        }

        if (requestParameters['grade'] != null) {
            queryParameters['grade[]'] = requestParameters['grade'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country[]'] = requestParameters['country'];
        }

        if (requestParameters['myTeams'] != null) {
            queryParameters['myTeams'] = requestParameters['myTeams'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{id}/teams`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Teams present at a given Event
     */
    async eventGetTeamsRaw(requestParameters: EventGetTeamsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTeam>> {
        const requestOptions = await this.eventGetTeamsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTeamFromJSON(jsonValue));
    }

    /**
     * Gets a List of Teams present at a given Event
     */
    async eventGetTeams(requestParameters: EventGetTeamsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTeam> {
        const response = await this.eventGetTeamsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const EventGetEventsLevelEnum = {
    World: 'World',
    National: 'National',
    State: 'State',
    Signature: 'Signature',
    Other: 'Other'
} as const;
export type EventGetEventsLevelEnum = typeof EventGetEventsLevelEnum[keyof typeof EventGetEventsLevelEnum];
/**
 * @export
 */
export const EventGetSkillsTypeEnum = {
    Driver: 'driver',
    Programming: 'programming'
} as const;
export type EventGetSkillsTypeEnum = typeof EventGetSkillsTypeEnum[keyof typeof EventGetSkillsTypeEnum];
/**
 * @export
 */
export const EventGetTeamsGradeEnum = {
    College: 'College',
    HighSchool: 'High School',
    MiddleSchool: 'Middle School',
    ElementarySchool: 'Elementary School'
} as const;
export type EventGetTeamsGradeEnum = typeof EventGetTeamsGradeEnum[keyof typeof EventGetTeamsGradeEnum];
