/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedProgram,
  Program,
} from '../models/index';
import {
    PaginatedProgramFromJSON,
    PaginatedProgramToJSON,
    ProgramFromJSON,
    ProgramToJSON,
} from '../models/index';

export interface ProgramGetProgramRequest {
    id: number;
}

export interface ProgramGetProgramsRequest {
    id?: Array<number>;
}

/**
 * 
 */
export class ProgramApi extends runtime.BaseAPI {

    /**
     * Creates request options for programGetProgram without sending the request
     */
    async programGetProgramRequestOpts(requestParameters: ProgramGetProgramRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling programGetProgram().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/programs/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Find a single Program by ID
     */
    async programGetProgramRaw(requestParameters: ProgramGetProgramRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Program>> {
        const requestOptions = await this.programGetProgramRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProgramFromJSON(jsonValue));
    }

    /**
     * Find a single Program by ID
     */
    async programGetProgram(requestParameters: ProgramGetProgramRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Program> {
        const response = await this.programGetProgramRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for programGetPrograms without sending the request
     */
    async programGetProgramsRequestOpts(requestParameters: ProgramGetProgramsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id[]'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/programs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Programs
     */
    async programGetProgramsRaw(requestParameters: ProgramGetProgramsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedProgram>> {
        const requestOptions = await this.programGetProgramsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedProgramFromJSON(jsonValue));
    }

    /**
     * Gets a List of Programs
     */
    async programGetPrograms(requestParameters: ProgramGetProgramsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedProgram> {
        const response = await this.programGetProgramsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
