/* tslint:disable */
/* eslint-disable */
/**
 * Public Robot Events API
 * An API to access data on Robot Events officially. ## Request Metadata Pagination is performed the same way throughout each pageable endpoint using query parameters `page` and `per_page` (per_page default is 25 with a maximum of 250). <br> Please note that dates should be formatted according to RFC3339. 
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaginatedAward,
  PaginatedEvent,
  PaginatedMatch,
  PaginatedRanking,
  PaginatedSkill,
  PaginatedTeam,
  Team,
} from '../models/index';
import {
    PaginatedAwardFromJSON,
    PaginatedAwardToJSON,
    PaginatedEventFromJSON,
    PaginatedEventToJSON,
    PaginatedMatchFromJSON,
    PaginatedMatchToJSON,
    PaginatedRankingFromJSON,
    PaginatedRankingToJSON,
    PaginatedSkillFromJSON,
    PaginatedSkillToJSON,
    PaginatedTeamFromJSON,
    PaginatedTeamToJSON,
    TeamFromJSON,
    TeamToJSON,
} from '../models/index';

export interface TeamGetAwardsRequest {
    id: number;
    event?: Array<number>;
    season?: Array<number>;
}

export interface TeamGetEventsRequest {
    id: number;
    sku?: Array<string>;
    season?: Array<number>;
    start?: Date;
    end?: Date;
    level?: Array<TeamGetEventsLevelEnum>;
}

export interface TeamGetMatchesRequest {
    id: number;
    event?: Array<number>;
    season?: Array<number>;
    round?: Array<number>;
    instance?: Array<number>;
    matchnum?: Array<number>;
}

export interface TeamGetRankingsRequest {
    id: number;
    event?: Array<number>;
    rank?: Array<number>;
    season?: Array<number>;
}

export interface TeamGetSkillsRequest {
    id: number;
    event?: Array<number>;
    type?: Array<TeamGetSkillsTypeEnum>;
    season?: Array<number>;
}

export interface TeamGetTeamRequest {
    id: number;
}

export interface TeamGetTeamsRequest {
    id?: Array<number>;
    number?: Array<string>;
    event?: Array<number>;
    registered?: boolean;
    program?: Array<number>;
    grade?: Array<TeamGetTeamsGradeEnum>;
    country?: Array<string>;
    myTeams?: boolean;
}

/**
 * 
 */
export class TeamApi extends runtime.BaseAPI {

    /**
     * Creates request options for teamGetAwards without sending the request
     */
    async teamGetAwardsRequestOpts(requestParameters: TeamGetAwardsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling teamGetAwards().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['event'] != null) {
            queryParameters['event[]'] = requestParameters['event'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season[]'] = requestParameters['season'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{id}/awards`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Awards that a given Team has received
     */
    async teamGetAwardsRaw(requestParameters: TeamGetAwardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedAward>> {
        const requestOptions = await this.teamGetAwardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedAwardFromJSON(jsonValue));
    }

    /**
     * Gets a List of Awards that a given Team has received
     */
    async teamGetAwards(requestParameters: TeamGetAwardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedAward> {
        const response = await this.teamGetAwardsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teamGetEvents without sending the request
     */
    async teamGetEventsRequestOpts(requestParameters: TeamGetEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling teamGetEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sku'] != null) {
            queryParameters['sku[]'] = requestParameters['sku'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season[]'] = requestParameters['season'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['level'] != null) {
            queryParameters['level[]'] = requestParameters['level'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{id}/events`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Events that a given Team has attended
     */
    async teamGetEventsRaw(requestParameters: TeamGetEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedEvent>> {
        const requestOptions = await this.teamGetEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedEventFromJSON(jsonValue));
    }

    /**
     * Gets a List of Events that a given Team has attended
     */
    async teamGetEvents(requestParameters: TeamGetEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedEvent> {
        const response = await this.teamGetEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teamGetMatches without sending the request
     */
    async teamGetMatchesRequestOpts(requestParameters: TeamGetMatchesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling teamGetMatches().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['event'] != null) {
            queryParameters['event[]'] = requestParameters['event'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season[]'] = requestParameters['season'];
        }

        if (requestParameters['round'] != null) {
            queryParameters['round[]'] = requestParameters['round'];
        }

        if (requestParameters['instance'] != null) {
            queryParameters['instance[]'] = requestParameters['instance'];
        }

        if (requestParameters['matchnum'] != null) {
            queryParameters['matchnum[]'] = requestParameters['matchnum'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{id}/matches`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Matches that a given Team has played in
     */
    async teamGetMatchesRaw(requestParameters: TeamGetMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedMatch>> {
        const requestOptions = await this.teamGetMatchesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedMatchFromJSON(jsonValue));
    }

    /**
     * Gets a List of Matches that a given Team has played in
     */
    async teamGetMatches(requestParameters: TeamGetMatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedMatch> {
        const response = await this.teamGetMatchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teamGetRankings without sending the request
     */
    async teamGetRankingsRequestOpts(requestParameters: TeamGetRankingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling teamGetRankings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['event'] != null) {
            queryParameters['event[]'] = requestParameters['event'];
        }

        if (requestParameters['rank'] != null) {
            queryParameters['rank[]'] = requestParameters['rank'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season[]'] = requestParameters['season'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{id}/rankings`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Rankings for a given Team
     */
    async teamGetRankingsRaw(requestParameters: TeamGetRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedRanking>> {
        const requestOptions = await this.teamGetRankingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedRankingFromJSON(jsonValue));
    }

    /**
     * Gets a List of Rankings for a given Team
     */
    async teamGetRankings(requestParameters: TeamGetRankingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedRanking> {
        const response = await this.teamGetRankingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teamGetSkills without sending the request
     */
    async teamGetSkillsRequestOpts(requestParameters: TeamGetSkillsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling teamGetSkills().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['event'] != null) {
            queryParameters['event[]'] = requestParameters['event'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type[]'] = requestParameters['type'];
        }

        if (requestParameters['season'] != null) {
            queryParameters['season[]'] = requestParameters['season'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{id}/skills`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Skills runs that a given Team has performed
     */
    async teamGetSkillsRaw(requestParameters: TeamGetSkillsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSkill>> {
        const requestOptions = await this.teamGetSkillsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSkillFromJSON(jsonValue));
    }

    /**
     * Gets a List of Skills runs that a given Team has performed
     */
    async teamGetSkills(requestParameters: TeamGetSkillsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSkill> {
        const response = await this.teamGetSkillsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teamGetTeam without sending the request
     */
    async teamGetTeamRequestOpts(requestParameters: TeamGetTeamRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling teamGetTeam().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a Single Team
     */
    async teamGetTeamRaw(requestParameters: TeamGetTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Team>> {
        const requestOptions = await this.teamGetTeamRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TeamFromJSON(jsonValue));
    }

    /**
     * Gets a Single Team
     */
    async teamGetTeam(requestParameters: TeamGetTeamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Team> {
        const response = await this.teamGetTeamRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for teamGetTeams without sending the request
     */
    async teamGetTeamsRequestOpts(requestParameters: TeamGetTeamsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id[]'] = requestParameters['id'];
        }

        if (requestParameters['number'] != null) {
            queryParameters['number[]'] = requestParameters['number'];
        }

        if (requestParameters['event'] != null) {
            queryParameters['event[]'] = requestParameters['event'];
        }

        if (requestParameters['registered'] != null) {
            queryParameters['registered'] = requestParameters['registered'];
        }

        if (requestParameters['program'] != null) {
            queryParameters['program[]'] = requestParameters['program'];
        }

        if (requestParameters['grade'] != null) {
            queryParameters['grade[]'] = requestParameters['grade'];
        }

        if (requestParameters['country'] != null) {
            queryParameters['country[]'] = requestParameters['country'];
        }

        if (requestParameters['myTeams'] != null) {
            queryParameters['myTeams'] = requestParameters['myTeams'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/teams`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a List of Teams
     */
    async teamGetTeamsRaw(requestParameters: TeamGetTeamsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedTeam>> {
        const requestOptions = await this.teamGetTeamsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedTeamFromJSON(jsonValue));
    }

    /**
     * Gets a List of Teams
     */
    async teamGetTeams(requestParameters: TeamGetTeamsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedTeam> {
        const response = await this.teamGetTeamsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const TeamGetEventsLevelEnum = {
    World: 'World',
    National: 'National',
    State: 'State',
    Signature: 'Signature',
    Other: 'Other'
} as const;
export type TeamGetEventsLevelEnum = typeof TeamGetEventsLevelEnum[keyof typeof TeamGetEventsLevelEnum];
/**
 * @export
 */
export const TeamGetSkillsTypeEnum = {
    Driver: 'driver',
    Programming: 'programming'
} as const;
export type TeamGetSkillsTypeEnum = typeof TeamGetSkillsTypeEnum[keyof typeof TeamGetSkillsTypeEnum];
/**
 * @export
 */
export const TeamGetTeamsGradeEnum = {
    College: 'College',
    HighSchool: 'High School',
    MiddleSchool: 'Middle School',
    ElementarySchool: 'Elementary School'
} as const;
export type TeamGetTeamsGradeEnum = typeof TeamGetTeamsGradeEnum[keyof typeof TeamGetTeamsGradeEnum];
